### PR TITLE
update python version on .github/workflows/testing.yaml

### PR DESCRIPTION
**Pull request by viktoriussuwandi**
[issue#462](https://github.com/sanders41/weather-command/issues/462)
Hi [sanders41](https://github.com/sanders41), python version on [.github/workflows/testing.yaml](https://github.com/sanders41/weather-command/blob/main/.github/workflows/testing.yaml) updated.

### CODE REVIEW

**Comment by sanders41** [comment]
@viktoriussuwandi your PR is good. The reason for the test failure is because `_cache.py` is missing `from __future__ import annotations` at the top of the file. This is actually why I wanted to make this update so things like this would be caught.

Do you want to make the update to add the import? If not it's fine, I can do it.

**Comment by sanders41** [comment]
Actually there is a better fix here because it is using pydantic. I'm going to push an update for you because it will be easier than explaining.

**Comment by viktoriussuwandi** [comment]
please go ahead @sanders41 thanks!

**Review by sanders41 — APPROVED** [review]
Alright we are good now. Thanks for this update, it's already payed off and caught an issue.

**Pull request merged**
