### PR TITLE
tomlkit replaced by tomli

### LINKED ISSUE #319: Replace tomlkit dependency with tomli
To do this: 

- [ ] remove tomlkit: `poetry remove tomlkit`
- [ ] install tomli: `poetry add --group=dev tomli --python "<3.11"`. `tomli` is only needed in python < 3.11 because 3.11 has it builtin as `tomllib`
- [ ] Change the imports in [test_main.py](https://github.com/sanders41/weather-command/blob/main/tests/test_main.py) from:

```py
import json
from pathlib import Path

import httpx
import pytest
from tomlkit import parse

from weather_command._config import LOCATION_BASE_URL
from weather_command.errors import MissingApiKey
from weather_command.main import __version__, app
```
to

```py
import json
from pathlib import Path

import httpx
import pytest

from weather_command._config import LOCATION_BASE_URL
from weather_command.errors import MissingApiKey
from weather_command.main import __version__, app

try:
    import tomli as tomllib  # type: ignore [import]
except ModuleNotFoundError:
    import tomllib  # type: ignore [no-redef]
```
- [ ] Change the `test_versions_match` test from:

```py
def test_versions_match():
    pyproject_file = Path().absolute() / "pyproject.toml"
    with open(pyproject_file, "r") as f:
        content = f.read()
        data = parse(content)
        pyproject_version = data["tool"]["poetry"]["version"]  # type: ignore
    assert __version__ == pyproject_version
```

to

```py
def test_versions_match():
    pyproject_file = Path().absolute() / "pyproject.toml"
    with open(pyproject_file, "rb") as f:
        data = tomllib.load(f)
        pyproject_version = data["tool"]["poetry"]["version"]
    assert __version__ == pyproject_version

```

### PR DESCRIPTION
**Pull request by Rishav1707**
## This PR closes the following issue:
closes #319

## Changes made:
https://github.com/sanders41/weather-command/issues/319#issue-1533126459

### CODE REVIEW

**Comment by sanders41** [comment]
Thanks @Rishav1707, everything you did looks correct. I'm not sure yet why mypy is passing locally but failing here.  I'm testing a solution now and should be able to merge this soon.

**Comment by Rishav1707** [comment]
> Thanks @Rishav1707, everything you did looks correct. I'm not sure yet why mypy is passing locally but failing here. I'm testing a solution now and should be able to merge this soon.

Ok @sanders41

**Comment by sanders41** [comment]
Alright looks like we got it now. These that won't fail locally, but fail in CI are always interesting to try to find fixes for :smile: 

Thanks for doing this!

**Review by sanders41 — APPROVED** [review]
Alright looks like we got it now. These that won't fail locally, but fail in CI are always interesting to try to find fixes for smile

Thanks for doing this!

**Pull request merged**
